Added Try/Except block for ImportError thrown by parse_requirements
barbacbd/nautical pull request #18
Opened 2022-05-14 00:20 UTC by samjtro

** pip.req was deprecated in pip v10 in favor of pip._internal.req
** Try/Except attempts to use the latest import scheme first, falling back to the earlier variant if an ImportError is thrown

2022-05-14 11:37 UTC, barbacbd requested changes
Reading through [this article](https://pip.pypa.io/en/latest/user_guide/#using-pip-from-your-program), I think we need to axe pip. I made the change to use a requirements file rather than hard coding them into the setup.py so that they could be used by others. We shouldn’t use pip in any Python code, would you mind reading in the file manually and passing those values to setup?

2022-05-14 17:25 UTC, samjtro commented
Totally agree on axing the pip internal library. I am traveling all day today, but I will get something written for that function and try to get it committed by tomorrow.

We could, alternatively, generate the "requirements.txt" file from setup.py after hard coding the requirements. That way, we don't need to mess around with reading in the file in setup.

Up to you though, I don't have a preference either way.

2022-05-17 00:22 UTC, barbacbd commented
Let's generate one from information stored in the setup that way we still have a reference.

2022-05-17 19:53 UTC, barbacbd commented
Based on further reading it appears that we want a setup.py (and a setup.cfg) as well as a requirements.txt. The requirements section and install requires are essentially duplicates with very different purposes (and audiences).

2022-05-18 02:34 UTC, closed without merging

2022-05-18 02:34 UTC, barbacbd commented
Sorry, I wanted to get the build running so it was passing all tests as a baseline. Thanks for the help! Pick up another if you are interested. I have quite a few more larger tickets coming soon.